name: BuildScriptJSENKTS
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout@v4
     - name: NPM
       uses: actions/setup-node@v4
       with:
         node-version: "20.x"
     - run: npm install -g typescript
       working-directory: ./exampleTS
     - run: tsc
       working-directory: ./exampleTS
     - run: npm pack
       working-directory: ./exampleTS/script
     - name: Upload Artifact
       uses: actions/upload-artifact@v4
       with:
         name: Example
         path: exampleTS/script/TestScriptJSENK2TS-1.0.0.tgz
