name: BuildScriptJSENKEsJS
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout@v4
     - name: NPM
       uses: actions/setup-node@v4
       with:
         node-version: "20.x"
     - run: npm i -g es.js @putout/bundle
       working-directory: ./exampleEsJS
     - run: esjs compilar . /script/
       working-directory: ./exampleEsJS
     - run: npm pack
       working-directory: ./exampleEsJS/script
     - name: Upload Artifact
       uses: actions/upload-artifact@v4
       with:
         name: ExampleEsJS
         path: exampleEsJS/script/TestScriptJSENK2EsJS-1.0.0.tgz
